name: Build backend deploy on server
on: 
  pull_request:
  push:
    branches:
      - main
jobs:
  build_and_preview:
    if: ${{ (github.event_name == 'push' && github.event.ref == 'refs/heads/main') || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH key
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Pull repo on server
      run: ssh ${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout main && git pull && npm ci && npm run build && systemctl restart dnd && exit"
    - name: Cleanup
      run: rm -rf ~/.ssh
      
